LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = yes
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no 
MAGIC_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes


UNICODE_ENABLE = yes
UNICODEMAP_ENABLE = no
